### ISSUE TITLE
ERROR (theano.graph.opt): Optimization failure due to: local_grad_log_erfc_neg

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/aesara#291]
From the PyMC discourse: https://discourse.pymc.io/t/theano-warnings-when-fitting-a-simple-psychometric-function-cumulative-normal-distribution/6650

**Please provide a minimal, self-contained, and reproducible example.**
```python
import numpy as np 
import pymc3 as pm 
import arviz as az 
from theano import tensor as tt                                         

def cumulative_normal(x, alpha, beta): 
  # Cumulative distribution function for the standard normal distribution 
  # return 0.5 + 0.5 * tt.erf((x-alpha)/(beta*tt.sqrt(2)))  # Works fine
  return 0.5 * (1 + tt.erf((x-alpha)/(beta*tt.sqrt(2)))) 

xij = np.array([-40.5, -40., 40.5]) 
nij = np.array([1.0, 0.0, 1.0])                                                                                      
rij = np.array([0, 0, 1.])  

with pm.Model(): 
  alpha = pm.Uniform('alpha', lower=-40.5, upper=40.5) 
  beta = pm.Uniform("beta", lower=10e-5, upper=40) 
  thetaij = pm.Deterministic('thetaij', cumulative_normal(xij, alpha, beta)) 
  # thetaij = pm.Deterministic('thetaij', pm.distributions.dist_math.std_cdf((xij-alpha)/beta))  # Also works fine
  rij_ = pm.Binomial('rij', p=thetaij, n=nij, observed=rij) 
  trace = pm.sample()
```

**Please provide the full traceback of any errors.**
```python
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
ERROR (theano.graph.opt): Optimization failure due to: local_grad_log_erfc_neg
ERROR (theano.graph.opt): node: Elemwise{true_div,no_inplace}(Elemwise{mul,no_inplace}.0, Elemwise{erfc,no_inplace}.0)
ERROR (theano.graph.opt): TRACEBACK:
ERROR (theano.graph.opt): Traceback (most recent call last):
  File "/home/ricardo/.local/lib/python3.8/site-packages/theano/graph/opt.py", line 2017, in process_node
    replacements = lopt.transform(fgraph, node)
  File "/home/ricardo/.local/lib/python3.8/site-packages/theano/graph/opt.py", line 1209, in transform
    return self.fn(*args, **kwargs)
  File "/home/ricardo/.local/lib/python3.8/site-packages/theano/tensor/opt.py", line 7307, in local_grad_log_erfc_neg
    if not exp_in.owner.inputs[0].owner:
AttributeError: 'NoneType' object has no attribute 'owner'
```
According to the user it still samples correctly.

Also, the equivalent `pm.distributions.dist_math.std_cdf` or `return 0.5 + 0.5 * tt.erf((x-alpha)/(beta*tt.sqrt(2)))` do not raise this warning.

## Versions and main components

* Aesara version: Theno 1.1.0
* PyMC version: 3.11.0
* Operating system: Linux

**Comment by brandonwillard** [comment]
To debug this, set `theano.config.on_opt_error = "raise"`.  That will prevent the exception from being caught and allow you to interactively debug.  Within the debugger, print the graph input to the function where the error occurs (i.e. `theano.tensor.opt.local_grad_log_erfc_neg`) using `theano.printing.debugprint`.

Those results provide us with the Theano/Aesara-only information that we need.
