### ISSUE TITLE
Aesara import with GPU fails

### ISSUE THREAD

**Issue by SyedMuhammadAli** [pymc-devs/aesara#320]
### When using "device = gpu" in .aesarac.txt
```python
>>> import aesara
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\syedali\AppData\Local\Programs\Python\Python36\lib\site-packages\aesara\__init__.py", line 62, in <module>
    from aesara.configdefaults import config
  File "C:\Users\syedali\AppData\Local\Programs\Python\Python36\lib\site-packages\aesara\configdefaults.py", line 1837, in <module>
    add_basic_configvars()
  File "C:\Users\syedali\AppData\Local\Programs\Python\Python36\lib\site-packages\aesara\configdefaults.py", line 347, in add_basic_configvars
    in_c_key=False,
  File "C:\Users\syedali\AppData\Local\Programs\Python\Python36\lib\site-packages\aesara\configparser.py", line 177, in add
    configparam.__get__(self, type(self), delete_key=True)
  File "C:\Users\syedali\AppData\Local\Programs\Python\Python36\lib\site-packages\aesara\configparser.py", line 361, in __get__
    self.__set__(cls, val_str)
  File "C:\Users\syedali\AppData\Local\Programs\Python\Python36\lib\site-packages\aesara\configparser.py", line 369, in __set__
    applied = self.apply(val)
  File "C:\Users\syedali\AppData\Local\Programs\Python\Python36\lib\site-packages\aesara\configparser.py", line 325, in apply
    return self._apply(value)
  File "C:\Users\syedali\AppData\Local\Programs\Python\Python36\lib\site-packages\aesara\configparser.py", line 464, in _apply
    "You are tring to use the old GPU back-end. "
ValueError: You are tring to use the old GPU back-end. It was removed from Aesara. Use device=cuda* now. See https://github.com/pymc-devs/aesara/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29 for more information.
```

### When using "device = cuda*" in .aesarac.txt
```python
>>> import aesara
ERROR (aesara.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType: None
```

## Versions and main components

* Aesara version: 2.02
* Aesara config (`python -c "import aesara; print(aesara.config)"`)
* Python version: 3.6.8
* Operating system: Windows 10
* How did you install Aesara: (pip install aesara)

**Comment by brandonwillard** [comment]
We aren't actively maintaining the GPU code in this fork at the moment, because we don't have easy access to GPUs in CI (see #47).  If anything, the `gpuarray` sub-package may be removed entirely in the near future.

Currently, the best approach to running Aesara code on a GPU is via the new JAX backend (i.e. `mode="JAX"`).
