### ISSUE TITLE
Fresh install Theano error

### ISSUE THREAD

**Issue by sammosummo** [pymc-devs/aesara#355]
## Totally fresh install, doesn't install Aesara, Theano-PyMC3 fails baby steps

After installation:

```python
from theano import *
import theano.tensor as T

# baby steps
x = T.dscalar('x')
y = T.dscalar('y')
z = x + y
f = function([x, y], z)
print(f(2, 3))
```

Produces this:

```python
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

You can find the C code in this temporary file: /var/folders/9w/4y2ckpfn4cz4y94fjg8jy9bm0000gn/T/theano_compilation_error_90qgq8as
library System is not found.
Traceback (most recent call last):
  File "/Users/samuelrobertmathias/PycharmProjects/FrequencyRT/in_theano.py", line 8, in <module>
    f = function([x, y], z)
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/compile/function/__init__.py", line 337, in function
    fn = pfunc(
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/compile/function/pfunc.py", line 524, in pfunc
    return orig_function(
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/compile/function/types.py", line 1981, in orig_function
    fn = m.create(defaults)
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/compile/function/types.py", line 1836, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/link/basic.py", line 266, in make_thunk
    return self.make_all(
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/link/vm.py", line 1131, in make_all
    node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/graph/op.py", line 634, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/graph/op.py", line 600, in make_c_thunk
    outputs = cl.make_thunk(
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/link/c/basic.py", line 1203, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/link/c/basic.py", line 1138, in __compile__
    thunk, module = self.cthunk_factory(
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/link/c/basic.py", line 1634, in cthunk_factory
    module = get_module_cache().module_from_key(key=key, lnk=self)
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/link/c/cmodule.py", line 1191, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/link/c/basic.py", line 1543, in compile_cmodule
    module = c_compiler.compile_str(
  File "/Users/samuelrobertmathias/miniconda3/envs/psychoacoustics/lib/python3.9/site-packages/theano/link/c/cmodule.py", line 2546, in compile_str
    raise Exception(
Exception: ('The following error happened while compiling the node', Elemwise{add,no_inplace}(x, y), '\n', 'Compilation failed (return status=1): ld: library not found for -lSystem. clang-11: error: linker command failed with exit code 1 (use -v to see invocation). ', 'FunctionGraph(Elemwise{add,no_inplace}(x, y))')
```

I'm not sure whether `conda-forge` needs to be updated to reflect the name change from Theano-pymc3 to Aesara or what, but currently pymc3 is unusable when install into a fresh env via Conda-forge on macOS.

## Versions and main components

* PyMC3 Version: 3.11.2 
* Aesara Version: theano-pymc-1.1.2  (**not Aesara?**)
* Python Version: 3.9.2
* Operating system: macOS 11.2.3
* How did you install PyMC3: `conda install -c conda-forge mkl pymc3`

**Comment by twiecki** [comment]
Can you try also installing `mkl-service`? It seems like blas is still being used.

**Comment by twiecki** [comment]
Can't find anything with `-lSystem`.

**Comment by sammosummo** [comment]
After `conda install mkl-service`, same issue.

**Comment by brandonwillard** [comment]
This is the Aesara repository.

**Comment by sammosummo** [comment]
@brandonwillard I don't understand the decision to move this over to the Aesara repo. PyMC3 does not use Aesara yet—it still installs Theano via `conda`. If the PyMC3 repo needs to be updated to use Aesara, then that is a PyMC3 issue, no?

@twiecki Confirmed, same issue with Aesara.

**Comment by brandonwillard** [comment]
> I don't understand the decision to move this over to the Aesara repo. PyMC3 does not use Aesara yet—it still installs Theano via `conda`. If the PyMC3 repo needs to be updated to use Aesara, then that is a PyMC3 issue, no?

The issue title, underlying problem, output, etc., is very specifically about PyMC3 + Theano(-PyMC), but this is the repository for _Aesara_.  Aesara has diverged quite a bit from Theano-PyMC, and builds for the latter were frozen a while back, so there's not much we can do with regards to Theano-PyMC failures.

If the problem is present within Aesara, then it needs to be reproduce in Aesara.

Otherwise, the error states that the linker cannot find the library `[lib]System`.  From a quick search, it seems like that's a Mac-specific library, and not one that's provided by any binary libraries associated with the Conda builds of Theano-PyMC/Aesara.  In other words, there's likely something wrong with your environment.

The only connection I can see to Conda is via `distutils`.  Aesara gets its library paths from `distutils`, and, if the Conda builds of Python are screwed up, you'll get bad compiler settings.  I've seen this before.  Regardless, we can't reasonably fix Conda package + environment issues within Aesara, so there might not be much we can do from this end.

As a work-around, you can attempt to manually add/fix the system library paths (e.g. `LD_LIBRARY_PATH` on Unix-likes) or change some of the [Aesara-configurable build options](https://aesara.readthedocs.io/en/latest/library/config.html).

**Comment by sammosummo** [comment]
I see, thanks. I assume that you will update PyMC3 to use Aesara rather than Theano-PyMC at some point.

After completely removing Miniconda and reinstalling, Theano-PyMC and Aesara now work as expected.

**Comment by brandonwillard** [comment]
> I see, thanks. I assume that you will update PyMC3 to use Aesara rather than Theano-PyMC at some point.

Yes, but I believe that will coincide with the release of PyMC version 4.

In the meantime, you can install a development build of PyMC3 from the repository and use Aesara.  The change is present there.



> **EDIT** The problem actually re-emerges when attempting to run through PyCharm. Running scripts from the terminal and interactive sessions are fine.

Yeah, as I recall, PyCharm and other IDEs often do not create proper shell environments, which&mdash;in turn&mdash;breaks anything that relies on a properly configured Conda environment.  The same is true for non-login shells.  I recently dealt with something like this, and the fix involved manually setting the `_CONDA_PYTHON_SYSCONFIGDATA_NAME` environment variable.
