### ISSUE TITLE
PyMC3 Fails on Windows Python 3.8 (Aesara dll imports)

### ISSUE THREAD

**Issue by hectormz** [pymc-devs/aesara#407]
## Description of your problem

Running `pymc3` on Windows fails for me when using python 3.8. Running the same code with same package versions on my machine with python 3.7 works. From what I can tell, this is a `Aesara` issue and not specifically a `pymc3` problem, but figured other users might find this issue in the future. I believe it is related to finding my `gcc` dlls, as it works if I add the `gcc` directory below.

It seems that the resolution of DLLs has changed in Python 3.8 for Windows:

> New in version 3.8: Previous versions of CPython would resolve DLLs using the default behavior for the current process. This led to inconsistencies, such as only sometimes searching PATH or the current working directory, and OS functions such as AddDllDirectory having no effect.

> DLL dependencies for extension modules and DLLs loaded with ctypes on Windows are now resolved more securely. Only the system paths, the directory containing the DLL or PYD file, and directories added with add_dll_directory() are searched for load-time dependencies. Specifically, PATH and the current working directory are no longer used, and modifications to these will no longer have any effect on normal DLL resolution. If your application relies on these mechanisms, you should check for add_dll_directory() and if it exists, use it to add your DLLs directory while loading your library. Note that Windows 7 users will need to ensure that Windows Update KB2533623 has been installed (this is also verified by the installer). (Contributed by Steve Dower in bpo-36085.)

* https://bugs.python.org/issue36085
* https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew
* https://docs.python.org/3/library/os.html#os.add_dll_directory

This is not a problem with `Anaconda`, which could be a solution for some folks.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
import numpy as np


# set the seed
np.random.seed(1)

n = 100 # The number of data points
X = np.linspace(0, 10, n)[:, None] # The inputs to the GP, they must be arranged as a column vector

# Define the true covariance function and its parameters
ℓ_true = 1.0
η_true = 3.0
cov_func = η_true**2 * pm.gp.cov.Matern52(1, ℓ_true)

# A mean function that is zero everywhere
mean_func = pm.gp.mean.Zero()

# The latent function values are one sample from a multivariate normal
# Note that we have to call `eval()` because PyMC3 built on top of Theano
f_true = np.random.multivariate_normal(mean_func(X).eval(),
                                       cov_func(X).eval() + 1e-8*np.eye(n), 1).flatten()

# The observed data is the latent function plus a small amount of T distributed noise
# The standard deviation of the noise is `sigma`, and the degrees of freedom is `nu`
e_true = 2.0
η_true = 3.0
y = f_true + e_true * np.random.standard_t(η_true, size=n)


with pm.Model() as model:
    ℓ = pm.Gamma("ℓ", alpha=2, beta=1)
    η = pm.HalfCauchy("η", beta=1)

    cov = η ** 2 * pm.gp.cov.Matern52(1, ℓ)
    gp = pm.gp.Latent(cov_func=cov)

    f = gp.prior("f", X=X)

    σ = pm.HalfCauchy("σ", beta=5)
    ν = pm.Gamma("ν", alpha=2, beta=0.1)
    y_ = pm.StudentT("y", mu=f, lam=1.0 / σ, nu=ν, observed=y)

    trace = pm.sample(1000, chains=2, cores=1, return_inferencedata=True)
```

**Please provide the full traceback.**
```python
WARNING (aesara.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "latent_var.py", line 22, in <module>
    f_true = np.random.multivariate_normal(mean_func(X).eval(),
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\graph.py", line 522, in eval
    self._fn_cache[inputs] = aesara.function(inputs, self)
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\compile\function.py", line 306, in function
    fn = pfunc(params=inputs,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\compile\pfunc.py", line 483, in pfunc
    return orig_function(inputs, cloned_outputs, mode,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\compile\function_module.py", line 1714, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\link.py", line 697, in make_thunk
    return self.make_all(input_storage=input_storage,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\vm.py", line 1087, in make_all
    thunks.append(node.op.make_thunk(node,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\op.py", line 954, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\op.py", line 857, in make_c_thunk
    outputs = cl.make_thunk(input_storage=node_input_storage,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\cc.py", line 1215, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\cc.py", line 1153, in __compile__
    thunk, module = self.cthunk_factory(error_storage,
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\cc.py", line 1623, in cthunk_factory
    module = get_module_cache().module_from_key(
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\cc.py", line 1520, in compile_cmodule
    module = c_compiler.compile_str(
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\cmodule.py", line 2405, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\hectormz\.virtualenvs\pymc3-venv-38\lib\site-packages\aesara\gof\cmodule.py", line 317, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed while importing m8f27cf6f6495a72b3883db0ff3f5d581f67a3adfd26460692f0372611b85620b: The specified module could not be found.
```

**Please provide any additional information below.**

I can fix this by adding the following chunk to https://github.com/pymc-devs/aesara/blob/2d3cb77530f8b80f60767c187ac6913740d0d996/aesara/link/c/cmodule.py#L289

```python
    if (sys.platform == "win32") & (hasattr(os, 'add_dll_directory')):
        gcc_path = shutil.which('gcc')
        if gcc_path is not None:
            os.add_dll_directory(os.path.dirname(gcc_path))
```
I'm sure this fix could go somewhere upstream, since `dlimport()` is called repeatedly

## Versions and main components

* Aesara version: 2.0.7
* Aesara config (`python -c "import aesara; print(aesara.config)"`)
```
[gcc]
cxxflags = -D_hypot=hypot
```
* Python version: 3.8.9
* Operating system: Windows 10
* How did you install Aesara: pip

**Comment by twiecki** [comment]
Thanks @hectormz! Want to do a PR with this fix?

**Comment by hectormz** [comment]
Gladly. If someone knows a more appropriate place to stick the chunk, let me know.

I tested this modification with `pymc3` and the most recent _tagged version_ of `Aesara`, because there have been some reorganizations of `Aesara` that `pymc3` doesn't know about yet.
